export const CREATE_CONSUL_REQUEST = 'CREATE_CONSUL_REQUEST'
export const CREATE_CONSUL_SUCCESS = 'CREATE_CONSUL_SUCCESS'
export const CREATE_CONSUL_FAIL = 'CREATE_CONSUL_FAIL'
export const CREATE_CONSUL_RESET = 'CREATE_CONSUL_RESET'


export const LIST_CONSUL_REQUEST = 'LIST_CONSUL_REQUEST'
export const LIST_CONSUL_SUCCESS = 'LIST_CONSUL_SUCCESS'
export const LIST_CONSUL_FAIL = 'LIST_CONSUL_FAIL'
export const LIST_CONSUL_RESET = 'LIST_CONSUL_RESET'

export const DELETE_CONSUL_REQUEST = 'DELETE_CONSUL_REQUEST'
export const DELETE_CONSUL_SUCCESS = 'DELETE_CONSUL_SUCCESS'
export const DELETE_CONSUL_FAIL = 'DELETE_CONSUL_FAIL'

export const UPDATE_CONSUL_REQUEST = 'UPDATE_CONSUL_REQUEST'
export const UPDATE_CONSUL_SUCCESS = 'UPDATE_CONSUL_SUCCESS'
export const UPDATE_CONSUL_FAIL = 'UPDATE_CONSUL_FAIL'
export const UPDATE_CONSUL_RESET = 'UPDATE_CONSUL_RESET'


export const DETAILS_CONSUL_REQUEST = 'DETAILS_CONSUL_REQUEST'
export const DETAILS_CONSUL_SUCCESS = 'DETAILS_CONSUL_SUCCESS'
export const DETAILS_CONSUL_FAIL = 'DETAILS_CONSUL_FAIL'


