export const LIST_CONSULT_REQUEST = 'LIST_CONSULT_REQUEST'
export const LIST_CONSULT_SUCCESS = 'LIST_CONSULT_SUCCESS'
export const LIST_CONSULT_FAIL = 'LIST_CONSULT_FAIL'
export const LIST_CONSULT_RESET = 'LIST_CONSULT_RESET'


export const CONSULT_DELETE_REQUEST = 'CONSULT_DELETE_REQUEST'
export const CONSULT_DELETE_SUCCESS = 'CONSULT_DELETE_SUCCESS'
export const CONSULT_DELETE_FAIL = 'CONSULT_DELETE_FAIL'


export const CONSULT_UPDATE_REQUEST = 'CONSULT_UPDATE_REQUEST'
export const CONSULT_UPDATE_SUCCESS = 'CONSULT_UPDATE_SUCCESS'
export const CONSULT_UPDATE_FAIL = 'CONSULT_UPDATE_FAIL'
export const CONSULT_UPDATE_RESET = 'CONSULT_UPDATE_RESET'


export const CONSULT_CREATE_REQUEST = 'CONSULT_CREATE_REQUEST'
export const CONSULT_CREATE_SUCCESS = 'CONSULT_CREATE_SUCCESS'
export const CONSULT_CREATE_FAIL = 'CONSULT_CREATE_FAIL'
export const CONSULT_CREATE_RESET = 'CONSULT_CREATE_RESET'

export const CONSULT_DETAILS_REQUEST = 'CONSULT_DETAILS_REQUEST'
export const CONSULT_DETAILS_SUCCESS = 'CONSULT_DETAILS_SUCCESS'
export const CONSULT_DETAILS_FAIL = 'CONSULT_DETAILS_FAIL'

export const CONSULT_USER_DETAILS_REQUEST = 'CONSULT_USER_DETAILS_REQUEST'
export const CONSULT_USER_DETAILS_SUCCESS = 'CONSULT_USER_DETAILS_SUCCESS'
export const CONSULT_USER_DETAILS_FAIL = 'CONSULT_USER_DETAILS_FAIL'

export const LIST_PAID_ENUMS_REQUEST = 'LIST_PAID_ENUMS_REQUEST'
export const LIST_PAID_ENUMS_SUCCESS = 'LIST_PAID_ENUMS_SUCCESS'
export const LIST_PAID_ENUMS_FAIL = 'LIST_PAID_ENUMS_FAIL'
export const LIST_PAID_ENUMS_RESET = 'LIST_PAID_ENUMS_RESET'