export const TEST_CATEGORY_CREATE_REQUEST = 'TEST_CATEGORY_CREATE_REQUEST'
export const TEST_CATEGORY_CREATE_SUCCESS = 'TEST_CATEGORY_CREATE_SUCCESS'
export const TEST_CATEGORY_CREATE_FAIL = 'TEST_CATEGORY_CREATE_FAIL'
export const TEST_CATEGORY__CREATE_RESET = 'TEST_CATEGORY__CREATE_RESET'